### ISSUE TITLE
Add support for `format: yaml` in secrets.yml

### ISSUE THREAD

**Issue by marklonquist** [BESTSELLER/harpocrates#199]
Currently we only support env and json.

Having access to yaml as well would be benificial to us in Brand Tech, as we have a few services where we currently envsubt on some config files before copying it to the correct location in our Dockerfiles.

We would be able to do without this if we had yaml support.

**Comment by ChristianGroentved** [comment]
created jira task https://bestjira.atlassian.net/browse/ES-2757 to get it done

**Comment by Gaardsholt** [comment]
Fixed by #200
